import { codeForEnglishName } from './countries';
import { UN_MEMBER_CODES } from './sovereignty';

/** ISO 3166-1 alpha-2 → continent bucket (Europe/Asia/Africa/Americas/Oceania). */
const CONTINENT_BY_CODE: Record<string, string> = {
  AD: 'Europe',
  AE: 'Asia',
  AF: 'Asia',
  AG: 'Americas',
  AL: 'Europe',
  AM: 'Asia',
  AO: 'Africa',
  AR: 'Americas',
  AT: 'Europe',
  AU: 'Oceania',
  AZ: 'Asia',
  BA: 'Europe',
  BB: 'Americas',
  BD: 'Asia',
  BE: 'Europe',
  BF: 'Africa',
  BG: 'Europe',
  BH: 'Asia',
  BI: 'Africa',
  BJ: 'Africa',
  BN: 'Asia',
  BO: 'Americas',
  BR: 'Americas',
  BS: 'Americas',
  BT: 'Asia',
  BW: 'Africa',
  BY: 'Europe',
  BZ: 'Americas',
  CA: 'Americas',
  CD: 'Africa',
  CF: 'Africa',
  CG: 'Africa',
  CH: 'Europe',
  CI: 'Africa',
  CL: 'Americas',
  CM: 'Africa',
  CN: 'Asia',
  CO: 'Americas',
  CR: 'Americas',
  CU: 'Americas',
  CV: 'Africa',
  CY: 'Asia',
  CZ: 'Europe',
  DE: 'Europe',
  DJ: 'Africa',
  DK: 'Europe',
  DM: 'Americas',
  DO: 'Americas',
  DZ: 'Africa',
  EC: 'Americas',
  EE: 'Europe',
  EG: 'Africa',
  ER: 'Africa',
  ES: 'Europe',
  ET: 'Africa',
  FI: 'Europe',
  FJ: 'Oceania',
  FM: 'Oceania',
  FR: 'Europe',
  GA: 'Africa',
  GB: 'Europe',
  GD: 'Americas',
  GE: 'Asia',
  GH: 'Africa',
  GM: 'Africa',
  GN: 'Africa',
  GQ: 'Africa',
  GR: 'Europe',
  GT: 'Americas',
  GW: 'Africa',
  GY: 'Americas',
  HN: 'Americas',
  HR: 'Europe',
  HT: 'Americas',
  HU: 'Europe',
  ID: 'Asia',
  IE: 'Europe',
  IL: 'Asia',
  IN: 'Asia',
  IQ: 'Asia',
  IR: 'Asia',
  IS: 'Europe',
  IT: 'Europe',
  JM: 'Americas',
  JO: 'Asia',
  JP: 'Asia',
  KE: 'Africa',
  KG: 'Asia',
  KH: 'Asia',
  KI: 'Oceania',
  KM: 'Africa',
  KN: 'Americas',
  KP: 'Asia',
  KR: 'Asia',
  KW: 'Asia',
  KZ: 'Asia',
  LA: 'Asia',
  LB: 'Asia',
  LC: 'Americas',
  LI: 'Europe',
  LK: 'Asia',
  LR: 'Africa',
  LS: 'Africa',
  LT: 'Europe',
  LU: 'Europe',
  LV: 'Europe',
  LY: 'Africa',
  MA: 'Africa',
  MC: 'Europe',
  MD: 'Europe',
  ME: 'Europe',
  MG: 'Africa',
  MH: 'Oceania',
  MK: 'Europe',
  ML: 'Africa',
  MM: 'Asia',
  MN: 'Asia',
  MR: 'Africa',
  MT: 'Europe',
  MU: 'Africa',
  MV: 'Asia',
  MW: 'Africa',
  MX: 'Americas',
  MY: 'Asia',
  MZ: 'Africa',
  NA: 'Africa',
  NE: 'Africa',
  NG: 'Africa',
  NI: 'Americas',
  NL: 'Europe',
  NO: 'Europe',
  NP: 'Asia',
  NR: 'Oceania',
  NZ: 'Oceania',
  OM: 'Asia',
  PA: 'Americas',
  PE: 'Americas',
  PG: 'Oceania',
  PH: 'Asia',
  PK: 'Asia',
  PL: 'Europe',
  PT: 'Europe',
  PW: 'Oceania',
  PY: 'Americas',
  QA: 'Asia',
  RO: 'Europe',
  RS: 'Europe',
  RU: 'Europe',
  RW: 'Africa',
  SA: 'Asia',
  SB: 'Oceania',
  SC: 'Africa',
  SD: 'Africa',
  SE: 'Europe',
  SG: 'Asia',
  SI: 'Europe',
  SK: 'Europe',
  SL: 'Africa',
  SM: 'Europe',
  SN: 'Africa',
  SO: 'Africa',
  SR: 'Americas',
  SS: 'Africa',
  ST: 'Africa',
  SV: 'Americas',
  SY: 'Asia',
  SZ: 'Africa',
  TD: 'Africa',
  TG: 'Africa',
  TH: 'Asia',
  TJ: 'Asia',
  TL: 'Asia',
  TM: 'Asia',
  TN: 'Africa',
  TO: 'Oceania',
  TR: 'Asia',
  TT: 'Americas',
  TV: 'Oceania',
  TW: 'Asia',
  TZ: 'Africa',
  UA: 'Europe',
  UG: 'Africa',
  US: 'Americas',
  UY: 'Americas',
  UZ: 'Asia',
  VA: 'Europe',
  VC: 'Americas',
  VE: 'Americas',
  VN: 'Asia',
  VU: 'Oceania',
  WS: 'Oceania',
  YE: 'Asia',
  ZA: 'Africa',
  ZM: 'Africa',
  ZW: 'Africa',
};

/** Continent for a stored (English) country name, or 'Other' if unknown. */
export function continentForName(englishName: string): string {
  const code = codeForEnglishName(englishName);
  return (code && CONTINENT_BY_CODE[code]) || 'Other';
}

/** The five continent buckets used by `continentForName`, in display order. */
export const CONTINENTS = ['Africa', 'Americas', 'Asia', 'Europe', 'Oceania'] as const;
export type Continent = (typeof CONTINENTS)[number];

/**
 * UN member states per continent — the "x of y" denominators for the
 * dashboard. Counted once from the authoritative UN list so the totals stay in
 * lock-step with `sovereignty.ts` (Africa 54, Asia 47, Europe 43, Americas 35,
 * Oceania 14 = 193). Non-members (Vatican/Taiwan) are excluded by construction.
 */
const UN_MEMBERS_BY_CONTINENT: Record<string, number> = (() => {
  const counts: Record<string, number> = {};
  for (const code of UN_MEMBER_CODES) {
    const continent = CONTINENT_BY_CODE[code];
    if (continent) counts[continent] = (counts[continent] ?? 0) + 1;
  }
  return counts;
})();

/** How many UN member states a continent contains (0 for an unknown bucket). */
export function unMembersInContinent(continent: string): number {
  return UN_MEMBERS_BY_CONTINENT[continent] ?? 0;
}

/** UN members per continent as a fresh record (e.g. `{ Europe: 43, ... }`). */
export function unMembersByContinent(): Record<string, number> {
  return { ...UN_MEMBERS_BY_CONTINENT };
}
